spring.application.name=escritores

# Base de datos MySQL en AWS RDS
spring.datasource.url=jdbc:mysql://sg-rds-mysql.clx2xb6nogbs.us-east-1.rds.amazonaws.com/historias_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin12
spring.datasource.password=Nunclear55

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
server.address=0.0.0.0

# JWT
app.jwt.secret=MiClaveSuperSecretaParaJwtDebeTenerAlMenos32Caracteres123456
app.jwt.access-expiration-seconds=3600
app.jwt.refresh-expiration-seconds=604800

# Logs opcionales
logging.level.org.springframework.security=DEBUG
