-- Script opcional para actualizar una BD existente.
-- Si usas spring.jpa.hibernate.ddl-auto=update, Hibernate puede crear estas columnas automáticamente.
-- Ejecuta este script si prefieres controlar manualmente los cambios en MySQL.

ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE arc ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE arc ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE chapter ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE chapter ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE character_skill ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE character_skill ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE content_report ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE content_report ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE email_verification_token ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE email_verification_token ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE global_notice ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE global_notice ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE idea ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE idea ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE item ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE item ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE media ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE skill ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE skill ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_character ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_character ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_comment ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_comment ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_event ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_event ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_favorite ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_favorite ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_rating ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_rating ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE story_view_log ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE story_view_log ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE user_change_history ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_change_history ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE user_follow ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_follow ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE user_sanction ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_sanction ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE user_session ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_session ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;
ALTER TABLE volume ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE volume ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS auditoria (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    action_name VARCHAR(30) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    entity_name VARCHAR(150) NOT NULL,
    record_id VARCHAR(80) NULL,
    user_id INT NULL,
    username VARCHAR(150) NULL,
    request_method VARCHAR(20) NULL,
    request_path VARCHAR(500) NULL,
    description VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
