spring.application.name=escritores

# URL de la base de datos (asegúrate de que el nombre 'tu_base_de_datos' exista)
spring.datasource.url=jdbc:mysql://localhost:3306/historias_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración extra para JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true